package generate

import (
	"fmt"
	"strings"

	"github.com/my-paas/core/plan"
)

// GenerateDockerfile produces a multi-stage Dockerfile from a BuildPlan.
func GenerateDockerfile(bp *plan.BuildPlan) string {
	if bp.Static {
		return generateStaticDockerfile(bp)
	}
	return generateAppDockerfile(bp)
}

func generateAppDockerfile(bp *plan.BuildPlan) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Auto-generated by My PaaS Core\n"))
	b.WriteString(fmt.Sprintf("# Provider: %s | Framework: %s\n\n", bp.Provider, bp.Framework))

	// --- Build stage ---
	b.WriteString(fmt.Sprintf("FROM %s AS builder\n", bp.BaseImage))
	b.WriteString("WORKDIR /app\n")

	// Copy dependency files first (for caching)
	for _, f := range getDependencyFiles(bp) {
		b.WriteString(fmt.Sprintf("COPY %s ./\n", f))
	}

	if bp.InstallCmd != "" {
		b.WriteString(fmt.Sprintf("RUN %s\n", bp.InstallCmd))
	}

	b.WriteString("COPY . .\n")

	if bp.BuildCmd != "" {
		b.WriteString(fmt.Sprintf("RUN %s\n", bp.BuildCmd))
	}

	// --- Runtime stage ---
	b.WriteString("\n")
	runtimeImage := getRuntimeImage(bp)
	b.WriteString(fmt.Sprintf("FROM %s\n", runtimeImage))
	b.WriteString("WORKDIR /app\n")

	// Copy build artifacts
	for _, cp := range getCopyInstructions(bp) {
		b.WriteString(cp + "\n")
	}

	// Environment variables
	if len(bp.EnvVars) > 0 {
		envParts := []string{}
		for k, v := range bp.EnvVars {
			envParts = append(envParts, fmt.Sprintf("%s=%s", k, v))
		}
		b.WriteString(fmt.Sprintf("ENV %s\n", strings.Join(envParts, " \\\n    ")))
	}

	// Expose ports
	for _, port := range bp.Ports {
		b.WriteString(fmt.Sprintf("EXPOSE %s\n", port))
	}

	b.WriteString(fmt.Sprintf("CMD %s\n", formatCmd(bp.StartCmd)))

	return b.String()
}

func generateStaticDockerfile(bp *plan.BuildPlan) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by My PaaS Core (static)\n\n")

	hasNodeBuild := bp.Provider == "node" && bp.BuildCmd != ""

	if hasNodeBuild {
		b.WriteString(fmt.Sprintf("FROM %s AS builder\n", bp.BaseImage))
		b.WriteString("WORKDIR /app\n")
		for _, f := range getDependencyFiles(bp) {
			b.WriteString(fmt.Sprintf("COPY %s ./\n", f))
		}
		if bp.InstallCmd != "" {
			b.WriteString(fmt.Sprintf("RUN %s\n", bp.InstallCmd))
		}
		b.WriteString("COPY . .\n")
		b.WriteString(fmt.Sprintf("RUN %s\n", bp.BuildCmd))
		b.WriteString("\n")
	}

	b.WriteString("FROM nginx:alpine\n")

	if hasNodeBuild {
		b.WriteString("COPY --from=builder /app/dist /usr/share/nginx/html\n")
	} else {
		b.WriteString("COPY . /usr/share/nginx/html\n")
	}

	b.WriteString("EXPOSE 80\n")
	b.WriteString("CMD [\"nginx\", \"-g\", \"daemon off;\"]\n")

	return b.String()
}

func getDependencyFiles(bp *plan.BuildPlan) []string {
	switch bp.Provider {
	case "node":
		return []string{"package*.json"}
	case "golang":
		return []string{"go.mod go.sum* ./"}
	case "python":
		return []string{"requirements*.txt pyproject.toml* uv.lock* ./"}
	case "rust":
		return []string{"Cargo.toml Cargo.lock* ./"}
	case "java":
		return []string{"pom.xml* build.gradle* ./"}
	case "php":
		return []string{"composer.json composer.lock* ./"}
	default:
		return []string{}
	}
}

func getRuntimeImage(bp *plan.BuildPlan) string {
	switch bp.Provider {
	case "golang":
		return "alpine:3.19"
	case "rust":
		return "debian:bookworm-slim"
	case "java":
		return "eclipse-temurin:" + bp.Version + "-jre-alpine"
	case "node":
		return "node:" + bp.Version + "-alpine"
	case "python":
		return "python:" + bp.Version + "-slim"
	case "php":
		return "php:" + bp.Version + "-fpm-alpine"
	default:
		return bp.BaseImage
	}
}

func getCopyInstructions(bp *plan.BuildPlan) []string {
	switch bp.Provider {
	case "golang":
		return []string{"COPY --from=builder /app/server ."}
	case "rust":
		name := "app"
		if bp.StartCmd != "" && strings.HasPrefix(bp.StartCmd, "./target/release/") {
			name = strings.TrimPrefix(bp.StartCmd, "./target/release/")
		}
		return []string{
			fmt.Sprintf("COPY --from=builder /app/target/release/%s .", name),
		}
	case "java":
		if strings.Contains(bp.BuildCmd, "gradle") {
			return []string{"COPY --from=builder /app/build/libs/*.jar app.jar"}
		}
		return []string{"COPY --from=builder /app/target/*.jar app.jar"}
	case "node":
		return []string{
			"COPY --from=builder /app/node_modules ./node_modules",
			"COPY --from=builder /app .",
		}
	case "python":
		return []string{
			"COPY --from=builder /opt/venv /opt/venv",
			"COPY --from=builder /app .",
			"ENV PATH=\"/opt/venv/bin:$PATH\"",
		}
	case "php":
		return []string{
			"COPY --from=builder /app .",
		}
	default:
		return []string{"COPY --from=builder /app ."}
	}
}

func formatCmd(cmd string) string {
	parts := strings.Fields(cmd)
	if len(parts) == 0 {
		return "[\"sh\"]"
	}
	quoted := make([]string, len(parts))
	for i, p := range parts {
		quoted[i] = fmt.Sprintf("\"%s\"", p)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
